---
title: "High School Seniors t Test"
output: 
  html_document:
    theme: cerulean
    code_folding: hide
---

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(DT)
library(pander)
library(readr)
library(car)

HSS <- read_csv("../../Data/HighSchoolSeniors.csv")
#Remember: select "Session, Set Working Directory, To Source File Location", and then play this R-chunk into your console to read the HSS data into R. 
```

<!-- Instructions

1. Use the HSS dataset in R to come up with a question that can be answered with a t Test. 

Here is a link to the survey given to the students that participated in the study:
https://ww2.amstat.org/censusatschool/pdfs/C@SQuestionnaire.pdf
(Use the link to learn about what each column of data in the data set represents.)

2. Establish why your question is interesting and rephrase the question using a statistical "null" and "alternative" hypothesis. (Hint, see the "Math 325 Notebook -> R Help -> R-Markdown Hints" page of your textbook for instructions on how to write mathematical hypotheses.)

3. Clearly answer your question using statistics. Be sure to compute a p-value and provide supporting numerical and graphical summaries.

Note: you can create "groups" from the data in many ways. For example, suppose you wanted to create a variable that grouped people according to whether they thought recycling was more important than conserving water. You could do this by:

```{r}
HSS <- HSS %>%
  mutate(recycling_than_water = ifelse(Importance_recycling_rubbish >	Importance_conserving_water, "Recycling More Important", "Water Conservation More Important"))
```

-->

## Background

Males vs Females, who has the fastest reaction time?

We looked at study done to measure High School Senior Tennis Players to measure their reaction time.

Hers a link to the study: https://ww2.amstat.org/education/cas/2.cfm

$$
  H_0: \mu_\text{ Female Group} = \mu_\text{ Male Group}
$$
$$ 
  H_a: \mu_\text{ Female Group} \neq \mu_\text{ Male Group}
$$
$$\alpha = 0.1$$

## Analysis


```{r}
# Ctrl + shift + c to comment out code.

# Filter out Tennis players from the HSS data set.
HSSTennisPlayers <- filter(HSS, Favourite_physical_activity == "Tennis")

# Do a t-test comparing Reaction time and Gender of HSS tennis players.
t.test(Reaction_time ~ Gender, data = HSSTennisPlayers, mu=0, alternative="two.sided", conf.level=0.95) %>%
  pander()
```



## {.tabset .tabset-pills}

### Hide

### Show

```{r}
# Diagnostic Check:
qqPlot(Reaction_time ~ Gender, data = HSSTennisPlayers, ylab="Reaction Time", xlab="Quantities?")

# Graphical Summary:
# Do a boxplot here.


# Filter out the home internet access types, broadband connection and dial-up connection.
# InternetAccess <- filter(HSS, Home_Internet_Access == "Yes - broadband connection" |         
                          # Home_Internet_Access == "Yes - dial-up connection")

# Do a t-test:
# t.test()

# Graphical Summary:

```



## Conclusion



